[project]
name = "cholo"
description = "first latin memecoin on Stacks"
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = []

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

[contracts.cholo]
path = "contracts/cholo.clar"
clarity_version = 2
epoch = 2.4