[project]
name = "cholo"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = []

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

[contracts.cholo-v1]
path = "contracts/cholo-v1.clar"
clarity_version = 2
epoch = 2.4